name: hello
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          [[ $BRANCH == "master" ]] && { echo "::set-env name=ROLE::${AWS_PRODUCTION_ROLE}" }
          [[ $BRANCH == "integration" ]] && { echo "::set-env name=ROLE::${AWS_INTEGRATION_ROLE}" }
