name: test
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          echo "::set-env name=BRANCH::master"

      - name: check
        run: |
          if [[ $BRANCH == "master" ]]; then
            echo "::set-env name=ROLE::PRODUCTION"
          elif [[ $BRANCH == "integration" ]]; then
            echo "::set-env name=ROLE::INTEGRATION"
          fi

      - name: print
        if: env.BRANCH == 'master'
        run: |
          echo "Role is ${ROLE}"
