name: test
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          echo "::set-env name=BRANCH::master"

      - name: check
        shell: bash
        run: |
          [[ $BRANCH == "master" ]] && echo "::set-env name=ROLE::A"
